replay_buffer_memory_size: 200000
replay_buffer_batch_size: 128
max_training_iterations: 300
replay_buffer_batch_size: 128
memory_learning_start: 40000
agent_learn_every_x_steps: 50
agent_learn_num_iterations: 10
success_threshold: 30.0
# Neural Network params
learning_rate: 0.001
actor_critic_weight_init_from: -0.0003
actor_critic_weight_init_to: 0.0003
optimizer_critic_weight_decay: 0.0000
noise_mu: [0.0, 0.0]
agent_gamma: 0.95
agent_tau: 0.01
noise_theta: 0.15
noise_sigma: 0.25
# these are more or less fixed parameters
local_tune_log_dir: tune_logs
render_human_view: False
video: False
sync_results: False
num_parallel_instances: 10
physics_engine: mujoco
env_obs_dim: 8
human_view_dim: [200, 200]
env_camera_number: 0
env_time_sleep: 0.0042
action_dim: 2
device: cuda
use_tune_tracking: False
gamma: 0.995
lambda_value: 0.96
ppo_epsilon: 0.2
ppo_epochs: 6
ppo_burnin_iterations: 20
critic_discount: 1.
entropy_beta: 0.02

cloud_folder: "depth_cam/"
experiment_epoch: 125
experiment_name: "weights"
env_config: {max_steps_in_environment: 600,
    render_human_view: False,
    video: False,
    env_obs_dim: [1, 84, 84],
    human_view_dim: [200, 200],
    env_camera_number: 3,
    env_time_sleep: 0.0042,
    action_dim: 4}
